about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('', views.about_pizzeria, name='about_pizzeria'),
]

homepage/urls.py
from django.urls import path
from . import views


app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
]

pizza/urls.py
from django.urls import path
from . import views


app_name = 'pizza'

urlpatterns = [
    path('', views.pizza_list, name='list'),
    path('<int:pk>', views.pizza_detail, name='detail')
]

pizzeria_online/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('pizza/', include('pizza.urls', namespace='pizza')),
    path('about/', include('about.urls', namespace='about'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

about/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

pizza/models.py
import os
from django.db import models


class PublishedModel(models.Model):
    """Абстрактная модель. Добавляет флаг is_published."""
    is_published = models.BooleanField('Опубликовано', default=True)

    class Meta:
        abstract = True


class Category(PublishedModel):
    title = models.CharField(
        'Название',
        max_length=256,
        help_text='Уникальное название категории, не более 256 символов'
    )
    output_order = models.PositiveSmallIntegerField(
        'Порядок отображения',
        default=1000,
        help_text='Целое число, чем меньше, тем выше в выборке',
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

        ordering = ("title",)

    def __str__(self):
        return self.title


class Pizza(PublishedModel):
    is_on_main = models.BooleanField('На главную', default=False)
    title = models.CharField(
        'Название',
        max_length=256,
        help_text='Уникальное название пиццы, не более 256 символов'
    )
    description = models.TextField(
        'Описание',
    )
    structure = models.TextField(
        'Состав',
    )
    size = models.PositiveSmallIntegerField(
        'Размер, см.',
        default=30,
        help_text='Целое число, по умолчанию 30',
    )
    output_order = models.PositiveSmallIntegerField(
        default=1000,
        verbose_name='Порядок отображения',
        help_text='Целое число, чем меньше, тем выше в выборке',
    )
    price = models.DecimalField(
        'Цена, руб.',
        max_digits=20,
        decimal_places=2,
        help_text='Десятичная дробь(2 знака после запятой), не более 20 знаков',
    )

    category = models.ManyToManyField(
        'Category',
        related_name='pizza',
        verbose_name='Категория',
    )

    image = models.ImageField('Фото', upload_to='pizza')

    def save(self, *args, **kwargs):
        try:
            this_record = Pizza.objects.get(id=self.id)
            if this_record.image != self.image:
                if os.path.isfile(this_record.image.path):
                    os.remove(this_record.image.path)
        except Pizza.DoesNotExist:
            pass

        super(Pizza, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if self.image and os.path.isfile(self.image.path):
            os.remove(self.image.path)
        super(Pizza, self).delete(*args, **kwargs)

    class Meta:
        verbose_name = 'Пицца'
        verbose_name_plural = 'Пиццы'

        ordering = ('output_order', 'title')

    def __str__(self):
        return self.title

about/views.py
from django.shortcuts import render


def about_pizzeria(request):
    tempalte_name = 'about/about_pizzeria.html'

    context = {}

    return render(request, tempalte_name, context)

homepage/views.py
from django.shortcuts import render
from django.db.models import Prefetch
from pizza.models import Pizza, Category


def home(request):
    template_name = 'homepage/home.html'

    pizza_list = (
        Pizza.objects
        .filter(
            is_on_main=True,
            is_published=True,
        )
        .order_by(
            'output_order',
            'title',
        )
        .prefetch_related(
            Prefetch(
                'category',
                queryset=Category.objects.filter(
                        is_published=True
                    ).order_by(
                        'output_order',
                        'title',
                    )
            )
        )
    )
    context = {
        'pizza_list': pizza_list,
    }
    return render(request, template_name, context)

pizza/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Prefetch, Q
from .models import Pizza, Category


def pizza_list(request):
    template_name = 'pizza/pizza_list.html'
    search_query = request.GET.get('search', '')
    pizza_list = (
        Pizza.objects
        .filter(
            Q(title__icontains=search_query) |
            Q(description__icontains=search_query) |
            Q(structure__icontains=search_query) |
            Q(category__title__icontains=search_query),
            is_published=True,
        )
        .order_by(
            'output_order',
            'title',
        )
        .distinct()
        .prefetch_related(
            Prefetch(
                'category',
                queryset=Category.objects.filter(
                    is_published=True,
                ).order_by(
                    'output_order',
                    'title',
                )
            )
        )
    )
    context = {
        'pizza_list': pizza_list,
    }

    return render(request, template_name, context)


def pizza_detail(request, pk):
    template_name = 'pizza/pizza_detail.html'

    pizza_det = get_object_or_404(
        Pizza.objects
        .filter(
            is_published=True,
        )
        .prefetch_related(
            Prefetch(
                'category',
                queryset=Category.objects.filter(
                        is_published=True
                    ).order_by(
                        'output_order',
                        'title',
                    )
            )
        ),
        pk=pk
    )
    context = {
        'pizza': pizza_det,
    }

    return render(request, template_name, context)

templates/about/about_pizzeria.html
{% extends "base.html" %}
{% block title %}
  Pizzeria Online. О пиццериях
{% endblock %}
{% block content %}
  <div class="container mt-5">
    <h1 class="pb-4 mb-0">Каталог Pizzeria Online</h1>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.png' %}" type="image">
    {% include "includes/user_account.html" %}
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>
      {% block title %}{% endblock %}
    </title>
  </head>
  <body>
    {% include "includes/header.html" %}
    <main class="pt-5 my-5">
      {% block content %}{% endblock %}
    </main>
    {% include "includes/footer.html" %}   
  </body>
</html>

templates/homepage/home.html
{% extends "base.html" %}
{% block title %}
  Pizzeria Online. Главная
{% endblock %}
{% block content %}
  <div class="container mt-5">
    <h1 class="pb-3 mb-0">Главная</h1>
    <center class="pb-3 mb-0">
      <h2>Любимые пиццы наших покупателей</h2>
    </center>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for pizza in pizza_list %}
        {% include "includes/pizza_card.html" %}
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© «Pizzeria online» Все права защищены.</p>
</footer> 

templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow-sm">
    <div class="container">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        {% with request.resolver_match.view_name as view_name %}            
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item pe-2">              
            <h4><a
              class="nav-link {% if view_name == 'homepage:home' %} active border border-info rounded-2 border-2 {% endif %}" 
              href="{% url 'homepage:home' %}"
              >
              Главная
            </a>
          </li>
          <li class="nav-item">
            <h4><a 
              class="nav-link {% if view_name == 'pizza:list' %} active border border-info rounded-2 border-2 {% endif %}" 
              href="{% url 'pizza:list' %}"
              >
              Каталог
            </a>
          </li>
          <h4><li class="nav-item">
            <a 
              class="nav-link {% if view_name == 'about:about_pizzeria' %} active border border-info rounded-2 border-2 {% endif %}"
              href="{% url 'about:about_pizzeria' %}"
            >
            О пиццериях
            </a> 
          </li>
        </ul>
        {% endwith %}
      </div> 

      <form class="d-flex me-4" method="GET" action="{% url 'pizza:list' %}">
        <input class="form-control me-2" type="search" name="search" placeholder="Поиск" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">Поиск</button>
      </form>

      <a class="navbar-brand" href="" data-bs-toggle="modal" data-bs-target="#UserAccountModal">
        <img src="{% static 'img/user/user-login.png' %}" height="50" class="d-inline-block align-top" alt="">           
      </a>  

    </div>
  </nav>
</header>

templates/includes/pizza_card.html
{% load static %}
<div class="col">
  <div class="card h-100 border-5">
    <a class="text-decoration-none" href="{% url "pizza:detail" pizza.id %}">
      <img 
          class="card-img-top" 
          src="{{ pizza.image.url }}">
    </a>
    <div class="card-body text-secondary"> 
      <h3 class="card-title text-dark">{{ pizza.title }}</h3>
      <span>
        {% for category in pizza.category.all %}
          <p class="badge bg-info"> {{ category }}</p>
        {% endfor%}
      </span>
      <h5 class="card-text text-dark">{{ pizza.description|truncatechars:40 }}</h5>
      <p class="card-text">{{ pizza.structure }}</p>
      <p class="card-text">{{ pizza.size }}см</p>
    </div>
    <div class="card-footer">
      <span class="d-flex justify-content-between align-items-center">
        <h4><span class="badge bg-secondary">{{ pizza.price }} ₽</span></h4>
        <a href="#" class="btn btn-primary">В корзину</a>
      </span>
    </div>
  </div>
</div>

templates/includes/user_account.html
<div class="modal fade" id="UserAccountModal" tabindex="-1" aria-labelledby="UserAccountModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="UserAccountModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" style="min-height: 1500px">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

templates/pizza/pizza_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Pizzeria Online. Пицца {{ pizza.title|lower }}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row mt-3">
      <h1 class="pb-2 mb-0">{{ pizza.title }}</h1>  
      <div class="col-12 col-md-6">
        <h4>
          {% for category in pizza.category.all %}
            <span class="badge bg-info"> {{ category }}</span>
          {% endfor%}
        </h4>
        <h2 class="text-dark">Описание</h2>
        <h5 class="text-secondary">{{ pizza.description }}</h5>
        <h4 class="text-dark">Состав</h4>
        <h5 class="text-secondary">{{ pizza.structure }}</h5>
        <h4 class="text-dark">Размер</h4>
        <h5 class="text-secondary">{{ pizza.size }}см</h5>  
      </div> 
      <div class="col-12 col-md-6 mb-3">
        <img 
          class="img-fluid" 
          height="640" width="480"
          src="{{ pizza.image.url }}"
          >  
      </div>
      <div class="d-flex justify-content-between align-items-center">
        <h2><span class="badge bg-secondary">{{ pizza.price }} ₽</span></h2>
        <a href="#" class="btn btn-primary">
          <h2>
            В корзину
          </h2>
        </a>
      </div> 
    </div>   
  </div> 
{% endblock %}

templates/pizza/pizza_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Pizzeria Online. Каталог 
{% endblock %}
{% block content %}
  <div class="container mt-5">
    <h1 class="pb-4 mb-0">Каталог Pizzeria Online</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for pizza in pizza_list %}
        {% include "includes/pizza_card.html" %}
      {% endfor %}
    </div>
  </div>
{% endblock %}